# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  last10lines_config = debug
endif
ifeq ($(config),release)
  last10lines_config = release
endif
ifeq ($(config),sanitizer)
  last10lines_config = sanitizer
endif

PROJECTS := last10lines

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

last10lines:
ifneq (,$(last10lines_config))
	@echo "==== Building last10lines ($(last10lines_config)) ===="
	@${MAKE} --no-print-directory -C . -f last10lines.make config=$(last10lines_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f last10lines.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  sanitizer"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   last10lines"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"